//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMachineACafe
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrinkType", Namespace="http://schemas.datacontract.org/2004/07/TheMachineACafe")]
    public enum DrinkType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COFFEE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TEA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHOCOLATE = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SugarLevel", Namespace="http://schemas.datacontract.org/2004/07/TheMachineACafe")]
    public enum SugarLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LITTLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEDUIM = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIGHT = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drink", Namespace="http://schemas.datacontract.org/2004/07/TheMachineACafe")]
    public partial class Drink : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TheMachineACafe.DrinkType MyDrinkTypeField;
        
        private TheMachineACafe.SugarLevel MySugarLevelField;
        
        private bool WithNoCupField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TheMachineACafe.DrinkType MyDrinkType
        {
            get
            {
                return this.MyDrinkTypeField;
            }
            set
            {
                this.MyDrinkTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TheMachineACafe.SugarLevel MySugarLevel
        {
            get
            {
                return this.MySugarLevelField;
            }
            set
            {
                this.MySugarLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WithNoCup
        {
            get
            {
                return this.WithNoCupField;
            }
            set
            {
                this.WithNoCupField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGetADrink")]
public interface IGetADrink
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetADrink/GetMeADrink", ReplyAction="http://tempuri.org/IGetADrink/GetMeADrinkResponse")]
    TheMachineACafe.Drink GetMeADrink(int UserID, TheMachineACafe.DrinkType requestedDrinkType, TheMachineACafe.SugarLevel _requestedSugarLevel, bool havingACup);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetADrink/GetMeADrink", ReplyAction="http://tempuri.org/IGetADrink/GetMeADrinkResponse")]
    System.Threading.Tasks.Task<TheMachineACafe.Drink> GetMeADrinkAsync(int UserID, TheMachineACafe.DrinkType requestedDrinkType, TheMachineACafe.SugarLevel _requestedSugarLevel, bool havingACup);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetADrink/GetMyFavouriteDrink", ReplyAction="http://tempuri.org/IGetADrink/GetMyFavouriteDrinkResponse")]
    TheMachineACafe.Drink GetMyFavouriteDrink(int UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetADrink/GetMyFavouriteDrink", ReplyAction="http://tempuri.org/IGetADrink/GetMyFavouriteDrinkResponse")]
    System.Threading.Tasks.Task<TheMachineACafe.Drink> GetMyFavouriteDrinkAsync(int UserID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGetADrinkChannel : IGetADrink, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetADrinkClient : System.ServiceModel.ClientBase<IGetADrink>, IGetADrink
{
    
    public GetADrinkClient()
    {
    }
    
    public GetADrinkClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetADrinkClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetADrinkClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetADrinkClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TheMachineACafe.Drink GetMeADrink(int UserID, TheMachineACafe.DrinkType requestedDrinkType, TheMachineACafe.SugarLevel _requestedSugarLevel, bool havingACup)
    {
        return base.Channel.GetMeADrink(UserID, requestedDrinkType, _requestedSugarLevel, havingACup);
    }
    
    public System.Threading.Tasks.Task<TheMachineACafe.Drink> GetMeADrinkAsync(int UserID, TheMachineACafe.DrinkType requestedDrinkType, TheMachineACafe.SugarLevel _requestedSugarLevel, bool havingACup)
    {
        return base.Channel.GetMeADrinkAsync(UserID, requestedDrinkType, _requestedSugarLevel, havingACup);
    }
    
    public TheMachineACafe.Drink GetMyFavouriteDrink(int UserID)
    {
        return base.Channel.GetMyFavouriteDrink(UserID);
    }
    
    public System.Threading.Tasks.Task<TheMachineACafe.Drink> GetMyFavouriteDrinkAsync(int UserID)
    {
        return base.Channel.GetMyFavouriteDrinkAsync(UserID);
    }
}
